//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 
namespace Aufbauwerk.Tools.GroupPolicyInstaller {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Setup {
        
        private string nameField;
        
        private string imageField;
        
        private SetupType typeField;
        
        private string fileNameField;
        
        private string parametersField;
        
        private SetupReboot rebootField;
        
        private bool exclusiveField;
        
        private bool logSuccessField;
        
        private bool removeOnSuccessField;
        
        public Setup() {
            this.parametersField = "";
            this.rebootField = SetupReboot.IfRequired;
            this.exclusiveField = false;
            this.logSuccessField = true;
            this.removeOnSuccessField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SetupType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SetupReboot.IfRequired)]
        public SetupReboot Reboot {
            get {
                return this.rebootField;
            }
            set {
                this.rebootField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Exclusive {
            get {
                return this.exclusiveField;
            }
            set {
                this.exclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool LogSuccess {
            get {
                return this.logSuccessField;
            }
            set {
                this.logSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RemoveOnSuccess {
            get {
                return this.removeOnSuccessField;
            }
            set {
                this.removeOnSuccessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SetupType {
        
        /// <remarks/>
        WindowsInstallerPackage,
        
        /// <remarks/>
        WindowsInstallerPatch,
        
        /// <remarks/>
        WindowsInstallerRemoval,
        
        /// <remarks/>
        WindowsUpdateFile,
        
        /// <remarks/>
        WindowsUpdateRemoval,
        
        /// <remarks/>
        PowerShellScript,
        
        /// <remarks/>
        Executable,
        
        /// <remarks/>
        ExecutableNoWindow,
        
        /// <remarks/>
        DeviceDriverFile,
        
        /// <remarks/>
        DeviceDriverFileInteractive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SetupReboot {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        IfRequired,
        
        /// <remarks/>
        Always,
    }
}
